## Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
pd.set_option('display.max_columns',None)
import warnings
warnings.filterwarnings('ignore')

In [2]:
df_player_stats = pd.read_csv("Player_stats.csv")

In [3]:
df_player_stats.head()

,fullName,season,runs,ballsFaced,out,Innings_batted,fours,sixes,Fifties,Hundreds,batting_avg,Batting_strike_rate,Batting_Quality,Batting_Frequency,Batting_Player_Impact,100_Factor,50_Factor,Batting_Impact_Score,balls_bowled,conceded,wickets,Innings_bowled,4W_haul,5W_haul,dots,foursConceded,sixesConceded,wides,noballs,maidens,total_overs_bowled,economy,Bowling_strike_rate,bowling_avg,Bowling_Quality,Bowling_Frequency,Bowling_Player_Impact,4W_factor,5W_factor,Bowling_Impact_Score
0,AB de Villiers,2008,95.0,98.0,5.0,6.0,5.0,1.0,0.0,0.0,19.00,96.94,0.72,16.33,11.76,0.00,0.00,11.76,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,AB de Villiers,2009,465.0,355.0,9.0,13.0,39.0,12.0,3.0,1.0,51.67,130.99,1.14,27.31,31.13,0.08,0.23,37.20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,AB de Villiers,2010,111.0,119.0,7.0,7.0,7.0,0.0,0.0,0.0,15.86,93.28,0.68,17.00,11.56,0.00,0.00,11.56,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,AB de Villiers,2011,312.0,243.0,9.0,13.0,21.0,14.0,2.0,0.0,34.67,128.40,1.02,18.69,19.06,0.00,0.15,20.49,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,AB de Villiers,2012,319.0,198.0,8.0,13.0,26.0,15.0,3.0,0.0,39.88,161.11,1.26,15.23,19.19,0.00,0.23,21.40,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [4]:
#df_player_stats_new = df_player_stats[df_player_stats['season'] != 2022]
df_player_stats_new = df_player_stats[['fullName','season','Batting_Player_Impact','Bowling_Impact_Score']].sort_values(by=['fullName','season'])

In [5]:
df_player_stats_new.head()

         fullName  season  Batting_Player_Impact  Bowling_Impact_Score
0  AB de Villiers    2008                  11.76                   0.0
1  AB de Villiers    2009                  31.13                   0.0
2  AB de Villiers    2010                  11.56                   0.0
3  AB de Villiers    2011                  19.06                   0.0
4  AB de Villiers    2012                  19.19                   0.0

In [6]:
df_player_stats_new[(df_player_stats_new['fullName'] == 'AB de Villiers') & 
                    (df_player_stats_new['season'] == 2010-1)]['Batting_Player_Impact'].values[0]

31.13

## Calculating mod_player batting and bowling impacts based on previous season

In [7]:
def calculate_mod_player_batting_impact(name,season):
    if season == 2008:
        return 0.0
    else:
        if len(df_player_stats_new[(df_player_stats_new['fullName'] == name) & (df_player_stats_new['season'] == season-1)]) == 1:
            return df_player_stats_new[(df_player_stats_new['fullName'] == name) & 
                    (df_player_stats_new['season'] == season-1)]['Batting_Player_Impact'].values[0]
        else:
            return np.nan
        
        
def calculate_mod_player_bowling_impact(name,season):
    if season == 2008:
        return 0.0
    else:
        if len(df_player_stats_new[(df_player_stats_new['fullName'] == name) & (df_player_stats_new['season'] == season-1)]) == 1:
            return df_player_stats_new[(df_player_stats_new['fullName'] == name) & 
                    (df_player_stats_new['season'] == season-1)]['Bowling_Impact_Score'].values[0]
        else:
            return np.nan

In [8]:
df_player_stats_new['mod_batting_player_impact'] = df_player_stats_new.apply(
    lambda x : calculate_mod_player_batting_impact(x['fullName'],x['season']),axis=1)

In [9]:
df_player_stats_new['mod_bowling_player_impact'] = df_player_stats_new.apply(
    lambda x : calculate_mod_player_bowling_impact(x['fullName'],x['season']),axis=1)

In [10]:
df_player_stats_new.head(33)

,fullName,season,Batting_Player_Impact,Bowling_Impact_Score,mod_batting_player_impact,mod_bowling_player_impact
0,AB de Villiers,2008,11.76,0.00,0.00,0.00
1,AB de Villiers,2009,31.13,0.00,11.76,0.00
2,AB de Villiers,2010,11.56,0.00,31.13,0.00
3,AB de Villiers,2011,19.06,0.00,11.56,0.00
4,AB de Villiers,2012,19.19,0.00,19.06,0.00
5,AB de Villiers,2013,19.55,0.00,19.19,0.00
6,AB de Villiers,2014,23.36,0.00,19.55,0.00
7,AB de Villiers,2015,29.09,0.00,23.36,0.00
8,AB de Villiers,2016,35.36,0.00,29.09,0.00
9,AB de Villiers,2017,18.11,0.00,35.36,0.00
10,AB de Villiers,2018,35.50,0.00,18.11,0.00
11,AB de Villiers,2019,27.38,0.00,35.50,0.00
12,AB de Villiers,2020,26.15,0.00,27.38,0.00
13,AB de Villiers,2021,16.88,0.00,26.15,0.00
14,Aakash Chopra,2008,5.82,0.00,0.00,0.00
15,Aakash Chopra,2009,8.17,0.00,5.82,0.00
16,Aaron Finch,2010,15.96,0.00,NaN,NaN
17,Aaron Finch,2011,5.29,0.00,15.96,0.00
18,Aaron Finch,2012,21.68,0.00,5.29,0.00
19,Aaron Finch,2013,25.20,2.72,21.68,0.00
20,Aaron Finch,2014,18.41,0.00,25.20,2.72
21,Aaron Finch,2015,5.28,0.00,18.41,0.00
22,Aaron Finch,2016,26.66,0.00,5.28,0.00
23,Aaron Finch,2017,16.48,0.00,26.66,0.00
24,Aaron Finch,2018,10.44,0.00,16.48,0.00
25,Aaron Finch,2020,16.67,0.00,NaN,NaN
26,Aaron Finch,2022,12.08,0.00,NaN,NaN
2299,Aavishkar Salvi,2009,0.00,10.20,NaN,NaN
2300,Aavishkar Salvi,2011,0.00,18.24,NaN,NaN
27,Abdul Samad,2020,11.24,2.38,NaN,NaN
28,Abdul Samad,2021,7.57,11.10,11.24,2.38
29,Abdul Samad,2022,1.30,0.00,7.57,11.10
30,Abdur Razzak,2008,0.00,0.00,0.00,0.00

In [11]:
df_player_stats_new['mod_batting_player_impact'].isna().sum()

706

## Imputing the NULL values with the means

In [12]:
df_player_stats_new["mod_batting_player_impact"] = df_player_stats_new["mod_batting_player_impact"].fillna(
                df_player_stats_new.groupby('fullName')['Batting_Player_Impact'].transform('mean'))

df_player_stats_new["mod_batting_player_impact"] = df_player_stats_new["mod_batting_player_impact"].apply(
                                                                lambda x : round(x,2))

In [13]:
df_player_stats_new["mod_bowling_player_impact"] = df_player_stats_new["mod_bowling_player_impact"].fillna(
                df_player_stats_new.groupby('fullName')['Bowling_Impact_Score'].transform('mean'))

df_player_stats_new["mod_bowling_player_impact"] = df_player_stats_new["mod_bowling_player_impact"].apply(
                                                                lambda x : round(x,2))

In [14]:
df_player_stats_new.head(33)

,fullName,season,Batting_Player_Impact,Bowling_Impact_Score,mod_batting_player_impact,mod_bowling_player_impact
0,AB de Villiers,2008,11.76,0.00,0.00,0.00
1,AB de Villiers,2009,31.13,0.00,11.76,0.00
2,AB de Villiers,2010,11.56,0.00,31.13,0.00
3,AB de Villiers,2011,19.06,0.00,11.56,0.00
4,AB de Villiers,2012,19.19,0.00,19.06,0.00
5,AB de Villiers,2013,19.55,0.00,19.19,0.00
6,AB de Villiers,2014,23.36,0.00,19.55,0.00
7,AB de Villiers,2015,29.09,0.00,23.36,0.00
8,AB de Villiers,2016,35.36,0.00,29.09,0.00
9,AB de Villiers,2017,18.11,0.00,35.36,0.00
10,AB de Villiers,2018,35.50,0.00,18.11,0.00
11,AB de Villiers,2019,27.38,0.00,35.50,0.00
12,AB de Villiers,2020,26.15,0.00,27.38,0.00
13,AB de Villiers,2021,16.88,0.00,26.15,0.00
14,Aakash Chopra,2008,5.82,0.00,0.00,0.00
15,Aakash Chopra,2009,8.17,0.00,5.82,0.00
16,Aaron Finch,2010,15.96,0.00,15.83,0.25
17,Aaron Finch,2011,5.29,0.00,15.96,0.00
18,Aaron Finch,2012,21.68,0.00,5.29,0.00
19,Aaron Finch,2013,25.20,2.72,21.68,0.00
20,Aaron Finch,2014,18.41,0.00,25.20,2.72
21,Aaron Finch,2015,5.28,0.00,18.41,0.00
22,Aaron Finch,2016,26.66,0.00,5.28,0.00
23,Aaron Finch,2017,16.48,0.00,26.66,0.00
24,Aaron Finch,2018,10.44,0.00,16.48,0.00
25,Aaron Finch,2020,16.67,0.00,15.83,0.25
26,Aaron Finch,2022,12.08,0.00,15.83,0.25
2299,Aavishkar Salvi,2009,0.00,10.20,0.00,14.22
2300,Aavishkar Salvi,2011,0.00,18.24,0.00,14.22
27,Abdul Samad,2020,11.24,2.38,6.70,4.49
28,Abdul Samad,2021,7.57,11.10,11.24,2.38
29,Abdul Samad,2022,1.30,0.00,7.57,11.10
30,Abdur Razzak,2008,0.00,0.00,0.00,0.00

In [15]:
df_player_stats_new['mod_batting_player_impact'].isna().sum()

0

## Removing 2008 season as it serves no practical purpose in modeling

In [16]:
df_player_stats_new = df_player_stats_new[df_player_stats_new['season'] != 2008]

In [17]:
df_player_stats_new.head()

,fullName,season,Batting_Player_Impact,Bowling_Impact_Score,mod_batting_player_impact,mod_bowling_player_impact
1,AB de Villiers,2009,31.13,0.0,11.76,0.0
2,AB de Villiers,2010,11.56,0.0,31.13,0.0
3,AB de Villiers,2011,19.06,0.0,11.56,0.0
4,AB de Villiers,2012,19.19,0.0,19.06,0.0
5,AB de Villiers,2013,19.55,0.0,19.19,0.0

In [18]:
df_test_player_stats = df_player_stats_new[df_player_stats_new['season'] == 2022]

In [19]:
df_player_stats_new['fullName'].unique()

array(['AB de Villiers', 'Aakash Chopra', 'Aaron Finch',
       'Aavishkar Salvi', 'Abdul Samad', 'Abhijeet Tomar',
       'Abhimanyu Mithun', 'Abhinav Manohar', 'Abhinav Mukund',
       'Abhishek Jhunjhunwala', 'Abhishek Nayar', 'Abhishek Raut',
       'Abhishek Sharma', 'Abrar Kazi', 'Abu Nechim', 'Adam Gilchrist',
       'Adam Milne', 'Adam Voges', 'Adam Zampa', 'Adil Rashid',
       'Aditya Dole', 'Aditya Tare', 'Adrian Barath', 'Aiden Blizzard',
       'Aiden Markram', 'Ajantha Mendis', 'Ajinkya Rahane',
       'Ajit  Chandila', 'Ajit Agarkar', 'Akash Deep', 'Akash Singh',
       'Akila Dananjaya', 'Akshath Reddy', 'Akshdeep Nath',
       'Albie Morkel', 'Alex Carey', 'Alex Hales', 'Alfonso Thomas',
       'Ali Murtaza', 'Alzarri Joseph', 'Aman Hakim Khan',
       'Ambati Rayudu', 'Amit Mishra', 'Amit Paunikar', 'Amit Singh',
       'Amit Uniyal', 'Anand Rajan', 'Andre Russell', 'Andrew Flintoff',
       'Andrew McDonald', 'Andrew Symonds', 'Andrew Tye',
       'Angelo Mathews', 'Aniket Choudhary', 'Anil Kumble',
       'Anirudh Singh', 'Ankeet Chavan', 'Ankit Bawne', 'Ankit Rajpoot',
       'Ankit Sharma', 'Ankit Soni', 'Anmolpreet Singh', 'Anrich Nortje',
       'Anuj Rawat', 'Anukul Roy', 'Anureet Singh', 'Anustup Majumdar',
       'Arindam Ghosh', 'Arshdeep Singh', 'Arun Karthik', 'Asad Pathan',
       'Ashish Nehra', 'Ashish Reddy', 'Ashok Dinda', 'Ashok Menaria',
       'Ashton Turner', 'Avesh Khan', 'Axar Patel', 'Ayush Badoni',
       'Azhar Bilakhia', 'Azhar Mahmood', 'Baba Indrajith',
       'Balachandra Akhil', 'Barinder Sran', 'Basil Thampi',
       'Ben Cutting', 'Ben Dunk', 'Ben Hilfenhaus', 'Ben Laughlin',
       'Ben Rohrer', 'Ben Stokes', 'Beuran Hendricks',
       'Bhanuka Rajapaksa', 'Bharat Chipli', 'Bhargav Bhatt',
       'Bhuvneshwar Kumar', 'Billy Stanlake', 'Biplab Samantray',
       'Bipul Sharma', 'Bodapati Sumanth', 'Brad Haddin', 'Brad Hodge',
       'Brad Hogg', 'Brendon McCullum', 'Brett Lee', 'Callum Ferguson',
       'Cameron White', 'Carlos Brathwaite', 'Chaminda Vaas',
       'Chandan Madan', 'Chandrasekar Ganapathy', 'Charl Langeveldt',
       'Chetan Sakariya', 'Chetanya Nanda', 'Cheteshwar Pujara',
       'Chidhambaram Gautam', 'Chris Gayle', 'Chris Green',
       'Chris Jordan', 'Chris Lynn', 'Chris Morris', 'Chris Woakes',
       'Clint McKay', 'Colin Ingram', 'Colin Munro',
       'Colin de Grandhomme', 'Corey Anderson', "D'Arcy Short",
       'Dale Steyn', 'Damien Martyn', 'Dan Christian', 'Daniel Christian',
       'Daniel Harris', 'Daniel Sams', 'Daniel Vettori', 'Daren Sammy',
       'Darren Bravo', 'Darshan Nalkande', 'Daryl Mitchell',
       'David Hussey', 'David Miller', 'David Warner', 'David Wiese',
       'David Willey', 'Davy Jacobs', 'Dawid Malan', 'Debabrata Das',
       'Deepak Chahar', 'Deepak Hooda', 'Devdutt Padikkal',
       'Devon Conway', 'Dewald Brevis', 'Dhawal Kulkarni', 'Dhruv Shorey',
       'Dilhara Fernando', 'Dillon du Preez', 'Dimitri Mascarenhas',
       'Dinesh Karthik', 'Dirk Nannes', 'Dishant Yagnik',
       'Domnic Muthuswami', 'Doug Bollinger', 'Doug Bracewell',
       'Dushmantha Chameera', 'Dwaine Pretorius', 'Dwaraka Ravi Teja',
       'Dwayne Bravo', 'Dwayne Smith', 'Eklavya Dwivedi', 'Eoin Morgan',
       'Evin Lewis', 'Fabian Allen', 'Faf du Plessis', 'Faiz Fazal',
       'Farhaan Behardien', 'Farveez Maharoof', 'Fazalhaq Farooqi',
       'Fidel Edwards', 'Gautam Gambhir', 'George Bailey',
       'George Garton', 'Glenn Maxwell', 'Glenn Phillips',
       'Gnaneswara Rao', 'Graeme Smith', 'Graham Napier',
       'Gurinder Sandhu', 'Gurkeerat Singh Mann', 'Hanuma Vihari',
       'Harbhajan Singh', 'Hardik Pandya', 'Hardus Viljoen',
       'Harmeet Singh', 'Harpreet Brar', 'Harpreet Singh', 'Harry Gurney',
       'Harshal Patel', 'Harshit Rana', 'Hashim Amla', 'Heinrich Klaasen',
       'Herschelle Gibbs', 'Hrithik Shokeen', 'Imran Tahir',
       'Iqbal Abdulla', 'Irfan Pathan', 'Ish Sodhi', 'Ishan Kishan',
       'Ishan Malhotra', 'Ishan Porel', 'Ishank Jaggi', 'Ishant Sharma',
       'Ishwar Pandey', 'Isuru Udana', 'Jacob Oram', 'Jacques Kallis',
       'Jagadeesha Suchith', 'Jalaj Saxena', 'Jamaluddin Syed Mohammad',
       'James Faulkner', 'James Franklin', 'James Hopes', 'James Neesham',
       'James Pattinson', 'Jaskaran Singh', 'Jason Behrendorff',
       'Jason Holder', 'Jason Roy', 'Jasprit Bumrah', 'Javon Searles',
       'Jayant Yadav', 'Jaydev Unadkat', 'Jean-Paul Duminy',
       'Jeevan Mendis', 'Jerome Taylor', 'Jesse Ryder', 'Jhye Richardson',
       'Jitesh Sharma', 'Joe Denly', 'Jofra Archer', 'Joginder Sharma',
       'Johan Botha', 'Johan van der Wath', 'John Hastings',
       'Jonny Bairstow', 'Jos Buttler', 'Josh Hazlewood', 'Josh Philippe',
       'Junior Dala', 'Justin Kemp', 'KC Cariappa', 'KL Rahul', 'KM Asif',
       'KP Appanna', 'Kagiso Rabada', 'Kamlesh Nagarkoti', 'Kamran Khan',
       'Kane Richardson', 'Kane Williamson', 'Karan Goel', 'Karan Sharma',
       'Karanveer Singh', 'Karn Sharma', 'Kartik Tyagi', 'Karun Nair',
       'Kedar Jadhav', 'Keemo Paul', 'Kemar Roach', 'Kevin Pietersen',
       'Kevon Cooper', 'Khaleel Ahmed', 'Kieron Pollard',
       'Krishmar Santokie', 'Krishnakant  Upadhyay', 'Krishnappa Gowtham',
       'Krunal Pandya', 'Kuldeep Sen', 'Kuldeep Yadav', 'Kuldip Yadav',
       'Kulwant Khejroliya', 'Kumar Kartikeya', 'Kumar Sangakkara',
       'Kusal Perera', 'Kyle Abbott', 'Kyle Jamieson',
       'Lakshmipathy Balaji', 'Lalit Yadav', 'Lasith Malinga',
       'Laxmi Shukla', 'Lee Carseldine', 'Lendl Simmons',
       'Liam Livingstone', 'Liam Plunkett', 'Lockie Ferguson',
       'Love Ablish', 'Luke Pomersbach', 'Luke Ronchi', 'Luke Wright',
       'Lukman Meriwala', 'Lungi Ngidi', 'M Shahrukh Khan', 'MS Dhoni',
       'Maheesh Theekshana', 'Mahela Jayawardene', 'Mahesh Rawat',
       'Mahipal Lomror', 'Manan Vohra', 'Mandeep Singh', 'Manish Pandey',
       'Manoj Tiwary', 'Manpreet Gony', 'Manprit Juneja',
       'Manvinder  Bisla', 'Marchant de Lange', 'Marco Jansen',
       'Marcus Stoinis', 'Mark Boucher', 'Mark Wood', 'Marlon Samuels',
       'Martin Guptill', 'Mashrafe Mortaza', 'Matheesha Pathirana',
       'Matt Henry', 'Matthew Hayden', 'Matthew Wade', 'Mayank Agarwal',
       'Mayank Markande', 'Michael Clarke', 'Michael Hussey',
       'Michael Klinger', 'Michael Lumb', 'Michael Neser',
       'Mitchell Johnson', 'Mitchell Marsh', 'Mitchell McClenaghan',
       'Mitchell Santner', 'Mitchell Starc', 'Mithun Manhas', 'Moeen Ali',
       'Mohammad Ashraful', 'Mohammad Kaif', 'Mohammad Nabi',
       'Mohammed Shami', 'Mohammed Siraj', 'Mohit Sharma',
       'Mohnish  Mishra', 'Mohnish Parmar', 'Mohsin Khan',
       'Moises Henriques', 'Monu Kumar', 'Morne Morkel', 'Morne van Wyk',
       'Mujeeb Ur Rahman', 'Mukesh Choudhary', 'Munaf Patel',
       'Murali Kartik', 'Murali Vijay', 'Murugan Ashwin',
       'Mustafizur Rahman', 'Muttiah Muralitharan', 'Naman Ojha',
       'Narayan Jagadeesan', 'Nathan Coulter-Nile', 'Nathan Ellis',
       'Nathan McCullum', 'Nathan Rimmington', 'Nathu Singh',
       'Navdeep Saini', 'Nayan Doshi', 'Nic Maddinson', 'Nicholas Pooran',
       'Nikhil Naik', 'Niraj Patel', 'Nitin Saini', 'Nitish Rana',
       'Nuwan Kulasekara', 'Obed McCoy', 'Odean Smith', 'Oshane Thomas',
       'Owais Shah', 'Padmanabhan Prasanth', 'Pankaj Singh',
       'Paras Dogra', 'Pardeep Sahu', 'Parthiv Patel', 'Parvez Rasool',
       'Parvinder Awana', 'Pat Cummins', 'Paul Collingwood',
       'Paul Valthaty', 'Pawan Negi', 'Pawan Suyal', 'Peter Handscomb',
       'Pinal Shah', 'Piyush Chawla', 'Prabhsimran Singh',
       'Pradeep Sangwan', 'Pragyan Ojha', 'Prasanth Parameswaran',
       'Prashant Chopra', 'Prashant Solanki', 'Prasidh Krishna',
       'Praveen Dubey', 'Praveen Kumar', 'Pravin Tambe',
       'Prayas Ray Barman', 'Prerak Mankad', 'Prithvi Raj',
       'Prithvi Shaw', 'Priyam Garg', 'Quinton de Kock', 'RP Singh',
       'Rahil Shaikh', 'Rahul Chahar', 'Rahul Dravid', 'Rahul Sharma',
       'Rahul Shukla', 'Rahul Tewatia', 'Rahul Tripathi', 'Raiphi Gomez',
       'Rajagopal Sathish', 'Rajat Bhatia', 'Rajat Patidar',
       'Rajesh Bishnoi', 'Raju Bhatkal', 'Raj\xa0Bawa', 'Ramandeep Singh',
       'Ramesh Powar', 'Ranadeb Bose', 'Rashid Khan', 'Rasikh Salam',
       'Rassie van der Dussen', 'Ravi Bishnoi', 'Ravi Bopara',
       'Ravi Rampaul', 'Ravichandran Ashwin', 'Ravindra Jadeja',
       'Ravisrinivasan Sai Kishore', 'Ray Price', 'Reetinder Sodhi',
       'Richard Levi', 'Ricky Bhui', 'Ricky Ponting', 'Rilee Rossouw',
       'Riley Meredith', 'Rinku Singh', 'Ripal Patel', 'Rishabh Pant',
       'Rishi Dhawan', 'Riyan Parag', 'Rob Quiney', 'Robin Peterson',
       'Robin Uthappa', 'Roelof van der Merwe', 'Rohan Gavaskar',
       'Rohan Raje', 'Rohit Sharma', 'Romario Shepherd', 'Ronit More',
       'Ross Taylor', 'Rovman Powell', 'Rusty Theron', 'Ruturaj Gaikwad',
       'Ryan Harris', 'Ryan McLaren', 'Ryan Ninan', 'Ryan ten Doeschate',
       'S Badrinath', 'Sachin Baby', 'Sachin Rana', 'Sachin Tendulkar',
       'Sachithra Senanayake', 'Sai Sudharsan', 'Sam Billings',
       'Sam Curran', 'Samuel Badree', 'Sanath Jayasuriya',
       'Sandeep Lamichhane', 'Sandeep Sharma', 'Sandeep Warrier',
       'Sanjay Bangar', 'Sanjay Yadav', 'Sanju Samson', 'Sarabjit Ladda',
       'Sarfaraz Khan', 'Saurabh Tiwary', 'Scott Boland',
       'Scott Kuggeleijn', 'Scott Styris', 'Sean Abbott', 'Shadab Jakati',
       'Shahbaz Ahmed', 'Shahbaz Nadeem', 'Shakib Al Hasan',
       'Shalabh Srivastava', 'Shane Bond', 'Shane Harwood', 'Shane Warne',
       'Shane Watson', 'Shardul Thakur', 'Shashank Singh', 'Shaun Marsh',
       'Shaun Tait', 'Sheldon Cottrell', 'Sheldon Jackson',
       'Sherfane Rutherford', 'Shikhar Dhawan', 'Shimron Hetmyer',
       'Shivam Dube', 'Shivam Mavi', 'Shivam Sharma', 'Shivil Kaushik',
       'Shoaib Ahmed', 'Shoaib Shaikh', 'Shreevats Goswami',
       'Shreyas Gopal', 'Shreyas Iyer', 'Shrikant Mundhe',
       'Shrikant Wagh', 'Shubham Agarwal', 'Shubman Gill',
       'Siddarth Kaul', 'Siddharth Chitnis', 'Siddharth Trivedi',
       'Siddhesh Lad', 'Simarjeet Singh', 'Simon Katich',
       'Sourav Ganguly', 'Sourav Sarkar', 'Sreenath Aravind', 'Sreesanth',
       'Sridharan Sriram', 'Srikar Bharat', 'Srikkanth Anirudha',
       'Steven Smith', 'Stuart Binny', 'Sudeep Tyagi', 'Sudhesan Midhun',
       'Sumit Narwal', 'Sunil Narine', 'Sunny Gupta', 'Sunny Singh',
       'Sunny Sohal', 'Suraj Randiv', 'Suresh Raina', 'Suryakumar Yadav',
       'Suyash Prabhudessai', 'Swapnil Asnodkar', 'Swapnil Singh',
       'T Natarajan', 'TP Sudhindra', 'Tabraiz Shamsi',
       'Tanmay Srivastava', 'Taruwar Kohli', 'Tejas Baroka',
       'Thalaivan Sargunam', 'Thilan Thushara', 'Thisara Perera',
       'Tilak Varma', 'Tillakaratne Dilshan', 'Tim David', 'Tim Paine',
       'Tim Seifert', 'Tim Southee', 'Tirumalasetti Suman', 'Tom Banton',
       'Tom Curran', 'Travis Birt', 'Travis Head', 'Trent Boult',
       'Tristan Stubbs', 'Tushar Deshpande', 'Tymal Mills',
       'Tyron Henderson', 'Udit Birla', 'Umesh Yadav', 'Umran Malik',
       'Unmukt Chand', 'Usman Khawaja', 'VVS Laxman', 'Vaibhav Arora',
       'Varun Aaron', 'Varun Chakravarthy', 'Veer Pratap Singh',
       'Venkatesh Iyer', 'Venugopal Rao', 'Vijay Shankar', 'Vijay Zol',
       'Vikram Singh', 'Vikramjeet Malik', 'Vinay Kumar', 'Virat Kohli',
       'Virat Singh', 'Virender Sehwag', 'Vishnu Vinod',
       'Wanindu Hasaranga de Silva', 'Washington Sundar', 'Wasim Jaffer',
       'Wayne Parnell', 'Wilkin Mota', 'Wriddhiman Saha', 'Yash Dayal',
       'Yashasvi Jaiswal', 'Yashpal Singh', 'Yo Mahesh', 'Yogesh Nagar',
       'Yogesh Takawale', 'Yusuf Abdulla', 'Yusuf Pathan', 'Yuvraj Singh',
       'Yuzvendra Chahal', 'Zaheer Khan'], dtype=object)

## Calculating relative batting and bowling impacts based on cumulative impacts

In [20]:
def calculate_rel_batting_impact_score(name):
    impact_scores = df_player_stats_new[df_player_stats_new['fullName'] == name].sort_values(by='season')['mod_batting_player_impact'].values
    cum_score = impact_scores[0]
    cum_impact_score_list = [impact_scores[0]]
    for i in range(1,len(impact_scores)):
        if(impact_scores[i] < impact_scores[i-1]):
            cum_score -= (impact_scores[i-1] - impact_scores[i])
        else:
            cum_score+=impact_scores[i]
        cum_impact_score_list.append(round(cum_score,2))
    return cum_impact_score_list

In [21]:
calculate_rel_batting_impact_score('Yusuf Abdulla')

[0.0, 0.0]

In [22]:
df_player_stats_new[df_player_stats_new['fullName'] == 'Anureet Singh']

,fullName,season,Batting_Player_Impact,Bowling_Impact_Score,mod_batting_player_impact,mod_bowling_player_impact
222,Anureet Singh,2009,0.00,10.65,2.90,5.12
223,Anureet Singh,2015,2.07,11.73,2.90,5.12
2326,Anureet Singh,2016,0.00,0.00,2.07,11.73
224,Anureet Singh,2017,10.56,0.00,0.00,0.00
225,Anureet Singh,2018,1.88,3.20,10.56,0.00

In [23]:
df_player_stats_new[df_player_stats_new['fullName'] == 'Anureet Singh'].sort_values(by='season')['mod_batting_player_impact'].values

array([ 2.9 ,  2.9 ,  2.07,  0.  , 10.56])

In [24]:
total_impact_scores_bat = []
for name in df_player_stats_new['fullName'].unique():
    cum_impact_score_list = calculate_rel_batting_impact_score(name)
    total_impact_scores_bat.extend(cum_impact_score_list)

In [25]:
def calculate_rel_bowling_impact_score(name):
    impact_scores = df_player_stats_new[df_player_stats_new['fullName'] == name].sort_values(by='season')['mod_bowling_player_impact'].values
    cum_score = impact_scores[0]
    cum_impact_score_list = [impact_scores[0]]
    for i in range(1,len(impact_scores)):
        if(impact_scores[i] < impact_scores[i-1]):
            cum_score -= (impact_scores[i-1] - impact_scores[i])
        else:
            cum_score+=impact_scores[i]
        cum_impact_score_list.append(round(cum_score,2))
    return cum_impact_score_list

In [26]:
total_impact_scores_bowl = []
for name in df_player_stats_new['fullName'].unique():
    cum_impact_score_list = calculate_rel_bowling_impact_score(name)
    total_impact_scores_bowl.extend(cum_impact_score_list)

In [27]:
len(total_impact_scores_bat)

2360

In [28]:
len(total_impact_scores_bowl)

2360

In [29]:
pd.Series(total_impact_scores_bowl).isna().sum()

0

In [30]:
df_player_stats_new['rel_batting_impact_score'] = total_impact_scores_bat
df_player_stats_new['rel_bowling_impact_score'] = total_impact_scores_bowl

In [31]:
df_player_stats_new.isna().sum()

fullName                     0
season                       0
Batting_Player_Impact        0
Bowling_Impact_Score         0
mod_batting_player_impact    0
mod_bowling_player_impact    0
rel_batting_impact_score     0
rel_bowling_impact_score     0
dtype: int64

## Validating Player relative impact scores

In [32]:
df_player_stats_new[df_player_stats_new['fullName'] == 'Yusuf Abdulla'].sort_values(by='season')['mod_batting_player_impact'].values

array([0., 0.])

In [33]:
df_player_stats_new.head()

,fullName,season,Batting_Player_Impact,Bowling_Impact_Score,mod_batting_player_impact,mod_bowling_player_impact,rel_batting_impact_score,rel_bowling_impact_score
1,AB de Villiers,2009,31.13,0.0,11.76,0.0,11.76,0.0
2,AB de Villiers,2010,11.56,0.0,31.13,0.0,42.89,0.0
3,AB de Villiers,2011,19.06,0.0,11.56,0.0,23.32,0.0
4,AB de Villiers,2012,19.19,0.0,19.06,0.0,42.38,0.0
5,AB de Villiers,2013,19.55,0.0,19.19,0.0,61.57,0.0

In [34]:
df_player_stats_new[df_player_stats_new['fullName'] == 'Yusuf Abdulla']

,fullName,season,Batting_Player_Impact,Bowling_Impact_Score,mod_batting_player_impact,mod_bowling_player_impact,rel_batting_impact_score,rel_bowling_impact_score
2515,Yusuf Abdulla,2009,0.0,20.10,0.0,12.51,0.0,12.51
2259,Yusuf Abdulla,2010,0.0,4.92,0.0,20.10,0.0,32.61

In [35]:
df_player_stats_new[df_player_stats_new['fullName'] == 'Hardik Pandya']

,fullName,season,Batting_Player_Impact,Bowling_Impact_Score,mod_batting_player_impact,mod_bowling_player_impact,rel_batting_impact_score,rel_bowling_impact_score
708,Hardik Pandya,2015,9.84,1.15,14.07,5.74,14.07,5.74
709,Hardik Pandya,2016,3.36,3.20,9.84,1.15,9.84,1.15
710,Hardik Pandya,2017,12.00,5.64,3.36,3.20,3.36,4.35
711,Hardik Pandya,2018,15.15,15.36,12.00,5.64,15.36,9.99
712,Hardik Pandya,2019,20.72,9.56,15.15,15.36,30.51,25.35
713,Hardik Pandya,2020,16.19,0.00,20.72,9.56,51.23,19.55
714,Hardik Pandya,2021,8.14,0.00,16.19,0.00,46.70,9.99
715,Hardik Pandya,2022,27.20,10.98,8.14,0.00,38.65,9.99

In [36]:
calculate_rel_batting_impact_score('Yusuf Abdulla')

[0.0, 0.0]

In [37]:
df_player_stats_final = df_player_stats_new[['fullName','season','rel_batting_impact_score','rel_bowling_impact_score']]

## Saving the Cumulative Player Stats into a csv file

In [38]:
df_player_stats_final.to_csv("Player_stats_final.csv",index=False)